# Generated by Django 5.1.7 on 2025-03-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('hit_points_max', models.IntegerField(default=10)),
                ('hit_points_current', models.IntegerField(default=10)),
                ('armor_class', models.IntegerField(default=10)),
                ('proficiency_bonus', models.IntegerField(default=2)),
                ('character_class', models.CharField(blank=True, max_length=50)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('initiative_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('config', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='token',
            name='color',
            field=models.CharField(default='#ef4444', max_length=7),
        ),
        migrations.AddField(
            model_name='token',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ruleset'),
        ),
    ]
